const dict = {
    "phrase": [
        "As a {{role}}, I want to {{verb}} {{noun}} so that I can {{verb}} {{adjective}} {{noun}} to {{verb}} {{adjective}} {{noun}}.",
        "We're Hiring! Are you our next {{adjective}} {{role}}? You will create {{adjective}} {{noun}} and work together with our {{adjective}} {{role}}.",
        "Aww crap, our {{adjective}} {{role}} messed up the {{adjective}} {{noun}} again. Now we are blocked! Please {{verb}} the {{noun}} so we can meet our sprint goal.",
	"HR announced that one {{adjective}} {{role}} didn't {{verb}} the {{noun}}. Therefore his/her contract has been terminated.",
	"CTO believes {{noun}} is the new hot thing. Therefore she hired 200 new {{adjective}} {{role}}s to implement it within the company.",
    ],
    "role": [
        "Product Owner",
        "Developer",
        "Scrum Master",
        "Stakeholder",
        "Release Train Engineer",
        "Product Manager",
        "Jira Engineer",
        "\"DevOps\" guy",
        "10x Engineer",
        "Developer Advocate",
        "Enterprise Architect",
        "Vendor Management",
        "CTO",
        "CEO",
        "Agile Coach",
    ],
    "noun": [
	    "ulag",
        "agile",
        "sprint",
        "SAFe",
        "comfagile",
        "scrum",
        "retrospective",
        "feature",
        "milestone",
        "planning",
        "PI",
        "review",
	    "SoDa",
	    "Software Development Agile",
	    "Burndown Chart",
        "increment",
        "kanban",
        "task",
        "mindset",
        "backlog",
        "user stories",
        "burn down",
        "LESS",
        "iteration",
        "commit",
        "freaky friday",
        "controversial",
        "misalignment",
        "Shane",
        "Lean",
        "story point",
        "Feedback",
        "DevOps",
        "Agile Style Script (ASS)",
        "Agile Cyborg Security (ACS)",
        "Fist of Five",
        "Time to Market",
        "daily standup",
        "deadline",
        "management",
        "KISS",
        "communication",
        "scrum board",
        "Jira",
        "deployment",
        "CI/CD",
        "prod Deployment",
        "dev Environment",
        "Metaverse",
        "big data",
        "AI",
        "MVP",
        "silo",
        "outcome",
        "velocity",
        "planning poker",
        "vision",
        "magic estimation",
        "timebox",
        "DoD",
        "product roadmap",
        "sprint boundary",
        "scrum values",
    ],
    "verb": [
        "review",
		"revel",
        "visualize",
        "monitor",
        "extrapolate",
        "improve",
        "improvise",
        "adapt",
        "overcome",
        "generate",
        "randomize",
        "mitigate",
        "overcommit",
        "increase",
        "deliver",
    ],
    "adjective": [
        "lean",
        "fast",
        "modern",
        "stupid",
        "awesome",
        "ugly",
        "attractive",
        "bald",
        "beautiful",
        "elegant",
        "fit",
        "angry",
        "clumsy",
        "grumpy",
        "huge",
        "massive",
        "handsome",
        "skinny",
        "lazy",
        "under-resourced",
        "goal-oriented",
        "time-boxed",
        "cross-functional",
        "self-organized",
        "releasable",
    ]

}


module.exports = dict
